const js = require("@eslint/js");
const prettier = require("eslint-config-prettier");

/** @type {import('eslint').Linter.FlatConfig[]} */
module.exports = [
  {
    ignores: [
      "node_modules/",
      ".freebuff/",
      ".git/",
      ".vercel/",
      "supabase/",
      "data/",
      "**/.env*",
      "package-lock.json",
    ],
  },

  js.configs.recommended,
  prettier,

  // ── Server-side rules ──
  {
    files: ["server/**/*.js", "api/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Buffer: "readonly",
        global: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        fetch: "readonly",
        TextDecoder: "readonly",
        AbortController: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
      "prefer-const": "warn",
      "no-var": "warn",
      "eqeqeq": ["warn", "always", { null: "ignore" }],
      "curly": ["warn", "all"],
      "no-throw-literal": "warn",
      "prefer-template": "warn",
      "no-trailing-spaces": "warn",
      "eol-last": ["warn", "always"],
      "no-multiple-empty-lines": ["warn", { max: 2, maxEOF: 1 }],
      "semi": ["warn", "always"],
      "quotes": ["warn", "double", { avoidEscape: true, allowTemplateLiterals: true }],
      "comma-dangle": ["warn", "always-multiline"],
      "no-undef": "error",
    },
  },

  // ── Frontend rules (public/js) ──
  {
    files: ["public/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        AbortController: "readonly",
        TextDecoder: "readonly",
        FileReader: "readonly",
        DataTransfer: "readonly",
        Blob: "readonly",
        URL: "readonly",
        FormData: "readonly",
        Event: "readonly",
        Prism: "readonly",
        state: "readonly",
        AgentAPI: "readonly",
        escHtml: "readonly",
        formatMessageHtml: "readonly",
        sanitizeText: "readonly",
        showToast: "readonly",
        dismissToast: "readonly",
        scrollToBottom: "readonly",
        addMessage: "readonly",
        sendToAgent: "readonly",
        stopGeneration: "readonly",
        clearAgent: "readonly",
        copyMsgText: "readonly",
        feedbackMessage: "readonly",
        regenerateResponse: "readonly",
        saveEditedMessage: "readonly",
        cancelEditMessage: "readonly",
        selectTheme: "readonly",
        toggleTheme: "readonly",
        syncThemePicker: "readonly",
        toggleMobileSidebar: "readonly",
        switchPanel: "readonly",
        closeSettings: "readonly",
        loadSettings: "readonly",
        saveSettings: "readonly",
        testApi: "readonly",
        toggleWebSearch: "readonly",
        toggleDeepThink: "readonly",
        attachFile: "readonly",
        removeAttachment: "readonly",
        checkAuthStatus: "readonly",
        handleAuthClick: "readonly",
        signOut: "readonly",
        toggleExportDropdown: "readonly",
        exportAsJSON: "readonly",
        copyConversationToClipboard: "readonly",
        exportConversation: "readonly",
        toggleGallery: "readonly",
        openGalleryImage: "readonly",
        closeLightbox: "readonly",
        clearGallery: "readonly",
        downloadImage: "readonly",
        saveGalleryToStorage: "readonly",
        restoreGalleryFromStorage: "readonly",
        updateGalleryBadge: "readonly",
        loadConversationList: "readonly",
        selectConversation: "readonly",
        deleteConversation: "readonly",
        createNewConversation: "readonly",
        autoGenerateTitle: "readonly",
        showWelcomeMessage: "readonly",
        filterConversations: "readonly",
        autoRestoreConversation: "readonly",
        loadModelsFromServer: "readonly",
        toggleModelDropdown: "readonly",
        filterModelDropdown: "readonly",
        closeModelDropdowns: "readonly",
        selectModelFromDropdown: "readonly",
        renderDropdownContent: "readonly",
        createFileFromCode: "readonly",
        toggleReasoning: "readonly",
        addLineNumbers: "readonly",
        copyCodeBlock: "readonly",
        CommandPalette: "readonly",

        // Shared state — defined with `let` in app.js, used across modules
        agentHistory: "writable",
        currentConversationId: "writable",
        conversations: "writable",
        attachedFiles: "writable",
        imageGallery: "writable",
        loadedModels: "writable",
        webSearchEnabled: "writable",
        deepThinkEnabled: "writable",
        currentAgentRequest: "writable",
        _streamText: "writable",
        suggestedQuestionsContainer: "writable",
        currentUser: "writable",

        // Internal functions in extracted modules (not on window, but used cross-module)
        setupFileInput: "writable",
        renderAttachments: "writable",
        setupDragDrop: "writable",
        handlePastedImage: "writable",
        showPastePreview: "writable",
        createSkeletonMessage: "writable",
        showSkeletonLoader: "writable",
        removeSkeletonLoader: "writable",
        closeExportDropdown: "writable",
        applyTheme: "writable",
        lightboxKeyHandler: "writable",
        renderGallery: "writable",
        renderConversationList: "writable",
        updateModelDropdownTrigger: "writable",
        showTooltip: "writable",
        hideTooltip: "writable",
        renderDropdownContent: "writable",
        selectModelFromDropdown: "writable",
        renderCodeBlock: "writable",
        buildCreateFileButton: "writable",
        detectFileName: "writable",
        generateFollowUpSuggestions: "writable",
        generateKeywordSuggestions: "writable",
        editUserMessage: "writable",
        typewriterEffect: "writable",
        addSuggestedQuestions: "writable",
        updateAuthUI: "writable",
        loadSidebarProfile: "writable",
        resetSidebarAvatar: "writable",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-var": "off",
      "prefer-const": "off",
      "eqeqeq": ["warn", "always", { null: "ignore" }],
      "no-undef": "error",
      "semi": ["warn", "always"],
      "quotes": ["warn", "double", { avoidEscape: true, allowTemplateLiterals: true }],
      "comma-dangle": ["warn", "always-multiline"],
      "eol-last": ["warn", "always"],
      "no-trailing-spaces": "warn",
    },
  },
];
